### ISSUE TITLE
Incompatibility with Terralith

### ISSUE THREAD

**Issue by orznick14** [Crystalis7/Hybrid-Beta#11]
I am unable to find Terralith biomes when using both of these mods together. Not sure if compatibility is possible though since I believe Terralith changes terrain gen as well.

**Comment by Crystalis7** [comment]
Hello - unfortunately, I do not think that compatibility is possible between these mods in the way that you want (assuming you want Terralith biomes generating in Hybrid Beta terrain) - it can only be a case of one of the two overriding the other. If you try using the datapack versions instead, you could see if the result changes depending on which of the two datapacks you put on the top of the list.
