### ISSUE TITLE
incompatable with version 1.19.4 and 1.20

### ISSUE THREAD

**Issue by No-Git-Tag** [Crystalis7/Hybrid-Beta#13]
Tested with normal installation of Minecraft. Any world created with v10.0.1/1.19.4 when updated with v10.0.1/1.20.1 on Minecraft 1.20 will fail to load. Prompts user to load world in safe mode then fails with "invalid or corrupted save data."

**Comment by Crystalis7** [comment]
Hello - I have tried to recreate this with the following steps

- Create a world in 1.19.4 using the datapack version v10.0.1/1.19.4
- Copy it to my 1.20 world saves folder
- Open the world folder, delete the datapack version v10.0.1/1.19.4, and add the datapack version v10.0.1/1.20.1
- Open the world in Minecraft 1.20

Following these steps, I have opened the world without any issues. 

I assume you're using the datapack rather than the mod? And are you running any mods on the side?

**Comment by No-Git-Tag** [comment]
orign

**Comment by No-Git-Tag** [comment]
It was tested on a fresh 1.19.4 and 1.20 instance, but there is a pre-existing 1.19.4 and 1.20 instance that do include many mods. And yes, i was using the datapack when testing.

**Comment by Crystalis7** [comment]
Do you mean you created the 1.19.4 world on a vanilla instance and then opened it on a vanilla instance of 1.20?

**Comment by No-Git-Tag** [comment]
Hello - Yes, The world was made in both vanilla 1.19.4 and 1.20. 

I retested with the following steps

1. I created a world in 1.19.4 (vanilla) with datapack version v0.10.1/1.19.4
2. Loaded a few chunks in a ~12*12 range and exited the world
3. Copied the world file onto the saves folder in the 1.20 (vanilla) instance
4. Opened world - Discovery: World can load with the v0.10.1/1.19.4 datapack and v0.10.1/1.20.1 together
5.  exited world and deleted the datapack version v0.10.1/1.19.4
6.  attempted to enter world with same results as the first test

Difference in second test and first test: Second test was loaded in vanilla 1.20 with both datapacks version v0.10.1/1.20.1 and v0.10.1/1.19.4 while the first one had the datapack version v0.10.1/1.19.4 deleted and replaced with v0.10.1/1.20.1

Results in both tests are the same - The world cannot load with the datapack version v0.10.1/1.20.1

I am sorry if this issue annoys you!

**Comment by Crystalis7** [comment]
This seems rather odd. 

In your first test, do you replace the the datapack version v0.10.1/1.19.4 with version v0.10.1/1.20.1 _before_ you load the world in 1.20.1, or after? That is the only thing I can think of.

Do you have any further error logs?

And no worries - it is not annoying, rather it is strange that you are getting an error in the first place!

**Comment by No-Git-Tag** [comment]
I am sorry that the abnormal issue!

Yes, on the first test i have replaced the datapack version v0.10.1./1.19.4 with version v0.10.1/1.20.1 before loading the world in 1.20.1 And there are no error logs that have appeared. 

The second test was loaded in 1.20 with both datapacks v0.10.1./1.19.4 and v0.10.1./1.20.1 and thereafter had the datapack version v0.10.1./1.19.4 deleted and still resulted in the world failing to load.

Would there be a way for me to enable logging in any way in relation to the world loading at all?

**Comment by Crystalis7** [comment]
Just as a control, does this happen if you create a vanilla world (no datapacks) in 1.19.4 and then you try and load it in 1.20?

You could check the logs by keeping the Minecraft Launcher open when you run Minecraft, or by using a third-party client like MultiMC (this is the one I use)

**Comment by No-Git-Tag** [comment]
Have made a new world without the datapack in 1.19.4 and it does load in 1.20.1

And i use XMCL (X-Minecraft launcher) as my launcher and enabled logs for the 1.20 instance and came with a log 

"Missing metadata in pack file/Hybrid.Beta.1.20.1.v0.10.1.zip" 

I hope the log can help with something in relation to this issue.

**Comment by Crystalis7** [comment]
Thank you for the log - it has actually helped me identify a mistake on my part. Did you download the pack from Planet Minecraft or the GitHub releases? If so, I think the version I uploaded there was not constructed correctly. Try downloading it again from Planet Minecraft, Modrinth, or GitHub. I have updated the file, and it should now hopefully work.

**Comment by No-Git-Tag** [comment]
I am very sure that I have downloaded from the GitHub. 

I have tested again with the same steps as always and it now works. Thank you for fixing the issue!
