### ISSUE TITLE
Birch Forest biomes do not generate

### ISSUE THREAD

**Issue by mortuusars** [Crystalis7/Hybrid-Beta#17]
All other biomes are there (except windswept ones, but i guess that's intended), but `/locate biome minecraft:birch_forest` or `old_growth_birch_forest` results in a `Could not find a biome of type "minecraft:birch_forest" within reasonable distance`.

**Comment by Crystalis7** [comment]
I should have updated the description of the main post, but I decided to remove birch forests for a couple of reasons:

- I needed to make space for the Cherry Grove biome in 1.20+
- I just don't like how Birch Forests look
