### ISSUE TITLE
Plains Village terrain issues

### ISSUE THREAD

**Issue by mortuusars** [Crystalis7/Hybrid-Beta#18]
Plains Village structures do not generate a "supporting terrain" underneath them. Which results in some houses partially or fully floating above the ground. 
Also, the ground (grass/dirt) is generating inside the structure in some cases.

Only plains villages are affected from my testing, other types are fine.

Here's some screenshots of it: 
(Taiga and snowy village houses have a "blob" of terrain under them, which helps to blend the structure better with surroundings)

![2023-12-30_06 26 21](https://github.com/Crystalis7/Hybrid-Beta/assets/65141267/334899ba-2008-4479-8c3a-ee64d5c58e94)
![2023-12-30_06 35 27](https://github.com/Crystalis7/Hybrid-Beta/assets/65141267/6e227767-eac3-42f7-9e9c-f815cb721265)
![2023-12-30_06 35 39](https://github.com/Crystalis7/Hybrid-Beta/assets/65141267/125a1226-537f-44fa-941a-31df571f5575)
![2023-12-30_07 00 35](https://github.com/Crystalis7/Hybrid-Beta/assets/65141267/dafd9140-dc2b-45ca-bf6e-56ef16f72e09)
![2023-12-30_07 01 38](https://github.com/Crystalis7/Hybrid-Beta/assets/65141267/116b876c-2124-4afe-97f9-fb7f353914ab)
![2023-12-30_07 02 05](https://github.com/Crystalis7/Hybrid-Beta/assets/65141267/b20c9a4e-4b0a-4ded-b669-9c3a8c10eb08)
![2023-12-30_07 02 28](https://github.com/Crystalis7/Hybrid-Beta/assets/65141267/4598a156-d510-4032-9064-5326c8563713)

**Comment by Crystalis7** [comment]
The dirt generating inside village structures is not something I was expecting. Thank you for raising.
