### ISSUE TITLE
Corrupted my world save - hybrid-beta-1.0.1 (Fabric 1.20.4)

### ISSUE THREAD

**Issue by Zorklis** [Crystalis7/Hybrid-Beta#19]
At first it crashed the game, then I launched it again and it said errors were found and I can't launch it. 
So I lost my world (no worries I made a backup 2 days ago, nothing but a few dirt blocks replaced).
I'm just reporting it, not gonna investigate as I don't wanna test this mod

**Comment by Crystalis7** [comment]
Are you running any other mods? Particularly world generation ones? Do you have any error logs?

**Comment by Zorklis** [comment]
I'm running around 190 other mods (fabric api, mod menu ,etc included), but those are optimization mods, it could also have been noxesium's fps experimental feature but that one was for UI.
On world generation mods, not really, structure mods like : abridged , additional structures, adorabuild structures, dungeons and taverns, totw additions, towns and towers.
The only other cause could've been noxesium experimental feature like I said, but that would be an odd one to mess with the world.
Tried Hybrid Beta 1.0.2+mod and it does not break the world, I'll try to launch with 1.0.1 hybrid in a minute

**Comment by Zorklis** [comment]
oh 1.0.1 is not available anymore. Tried the Noxesium experimental feature.. it was probably that since it did crash the game.
