### ISSUE TITLE
[Question] Increase cave entrances

### ISSUE THREAD

**Issue by Insane96** [Crystalis7/Hybrid-Beta#27]
I see very few cave entrances (and the ones that are there end in nothing pretty quick as mentioned in #20)
There's anyway to move back up the cave entrances?
![image](https://github.com/Crystalis7/Hybrid-Beta/assets/7185104/7af38f1c-201f-46e4-9a36-19900f903170)

**Comment by Crystalis7** [comment]
Hi - thank you for raising - I have addressed this issue in v1.0.4. Please let me know if the issue has been resolved.

**Comment by Insane96** [comment]
Is 1.0.4 compatible with 1.20.1?

**Comment by ivanovic77** [comment]
Crystalis7, can you fix the cave entrance issue for the 1.20.1 version? Many modpacks relying on Create and other important mods are still in that version.

**Comment by Crystalis7** [comment]
This has been addressed in #34 .
