### ISSUE TITLE
Lack of cave entrances and too many flooded caves in version 1.0.3 for Minecraft 1.20.x

### ISSUE THREAD

**Issue by ivanovic77** [Crystalis7/Hybrid-Beta#34]
Firstly, congratulations Crystalis for this amazing mod. I've been looking for a terrain like this for a while. 

Is it possible to add the fix for the lack of cave entrances of 1.0.4 to the 1.0.3 version for Minecraft 1.20.x? Bear in mind that many modpacks relying on Create and other important mods are still in 1.20.1.

Besides, there are too many flooded caves near the surface. I don't know if there's an easy fix for that.

Thanks in advance.

**Comment by Crystalis7** [comment]
Hello - I'm glad you like the mod. 

I have now ported the v1.0.4 changes to 1.20.x (both mod and datapack).

Regarding the flooded caves issue, there does not seem to be a simple fix in the current state of datapack technology. It is a side-effect of the crazy terrain.

I hope this helps.

**Comment by ivanovic77** [comment]
Thank you!

I'll use it in the new server I'm building.
