### ISSUE TITLE
1.18.2 Datapack failed to validate

### ISSUE THREAD

**Issue by BastardNeko** [Crystalis7/Hybrid-Beta#4]
I'm trying to make this work, but whenever I put this into the datapack folder when creating a new world, it tells me that datapack failed to validate or something like that and doesn't let me add it. I have one mod that adds a few biomes. Is this why? Yes, I tried moving it down the list so it was right above the default datapack, same result.

**Comment by Crystalis7** [comment]
Which mod are you using, and does the datapack work when the mod isn't loaded?

**Comment by BastardNeko** [comment]
Terralith and Chinjufu mod. No. I disabled those and it still gave me this. I haven't tried disabling these, but i also have Botania, Awesome Dungeons mods, Yungs better strongholds, and a couple of dimmension mods including Twilight Forest, The Undergaden, The Bumblezone, and the Endergenic Expansion.
![Screenshot (58)](https://user-images.githubusercontent.com/53849104/203326491-b449b73f-6eae-4f37-9811-fb80cf711ebf.png)

**Comment by BastardNeko** [comment]
Don't know if this makes a difference, but I'm using forge.

**Comment by Crystalis7** [comment]
I have now published a hotfix for this issue.

**Comment by BastardNeko** [comment]
Yep. Hotfix worked.
