### ISSUE TITLE
Still Fails Validation

### ISSUE THREAD

**Issue by erazare** [Crystalis7/Hybrid-Beta#5]
pack still fails validation.. cant be added to a game.. i did this with 43.1.52 - 43.1.57 same result.. completely fresh install only your pack no mods.. it doesnt validate.

**Comment by Crystalis7** [comment]
It seems that the versions of Forge you mention are for 1.19.2. The hotfix I published yesterday was for 1.18.2. I have now published a similar hotfix (v0.9.4) which should hopefully fix your issues. Please try it out and let me know.

**Comment by erazare** [comment]
You are correct sorry.. Also used this with latest fabric, gorgeous looks
awesome.

**Comment by erazare** [comment]
This is NOT  fixed. 1.18 branch works, 1.19.2 works with FABRIC it does NOT
work with forge.
