### ISSUE TITLE
BYG and Hybrid Beta crashing to desktop when generating chunks

### ISSUE THREAD

**Issue by leader425** [Crystalis7/Hybrid-Beta#7]
The issue is pretty fundmental it seems replicating the error should be as simple as using the two mods together, seems to be a pretty core conflict as removing the biomes mentioned in the error just simply makes the error occur with different biomes untill the datapack no longer adds any biomes so it seems like its conflicting with how it generates biomes

**Comment by leader425** [comment]
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:bamboo_jungle]=net.minecraft.class_1959@3f9ed626}, Reference{ResourceKey[minecraft:worldgen/biome / byg:guiana_shield]=net.minecraft.class_1959@340fb26d}, Reference{ResourceKey[minecraft:worldgen/biome / byg:crag_gardens]=net.minecraft.class_1959@9ed305e}]

**Comment by leader425** [comment]
https://mclo.gs/L9TtNsE

**Comment by Crystalis7** [comment]
Do these conflicts exist with other terrain generation datapacks that add biomes?

**Comment by Crystalis7** [comment]
From the error logs, it seems to be to do with the biome trying to add in its own features to the biome class, and since the order of their definition matters, a conflict is caused.

**Comment by Crystalis7** [comment]
I have identified the issue and am in the process of fixing.

**Comment by leader425** [comment]
Damn that was extremely fast and no i had not tested it with othee biomes thanks though dude

**Comment by Crystalis7** [comment]
I have published a fix on PMC/Git as a pre-release. Please do test it and let me know if it fixes your issues

**Comment by leader425** [comment]
Yup seems to work on my end and alls good nice

**Comment by Crystalis7** [comment]
Awesome - thanks.
