### ISSUE TITLE
Frozen rivers are broken and general river issues with biomes

### ISSUE THREAD

**Issue by AnnPon** [Crystalis7/Hybrid-Beta#8]
Frozen rivers have ice in the middle that doesn't reach the coast due to their biome getting cut off.
![2023-02-23_00 54 39](https://user-images.githubusercontent.com/116905639/220903894-f9cb5d83-d2cc-4f5f-9e85-2dc4b71fd799.png)

Some smaller biomes can end up getting mostly cut off by being sunk.

**Comment by Crystalis7** [comment]
Hello - thank you for raising this. I will include a fix for it in the next feature update.

**Comment by Crystalis7** [comment]
This should now be fixed in the 1.0 update.
