### ISSUE TITLE
Can't find certain biomes

### ISSUE THREAD

**Issue by LionCat3125** [Crystalis7/Hybrid-Beta#9]
I'm not an expert on beta 1.7.3 world generation, but i can't find certain biomes
I spawned in a badlands biome and only found a savanna,a jungle,and a desert.
Next world, spawned in a taiga and found a snowy taiga, and a frozen ocean
Do i need to explore more?

**Comment by r-miladi** [comment]
You probably do need to explore more. The biomes should be similarly-sized and similarly-positioned compared with vanilla 1.19, so it should be possible to find all different biomes within a reasonable distance.

**Comment by Crystalis7** [comment]
You probably do need to explore more. The biomes should be similarly-sized and similarly-positioned compared with vanilla 1.19, so it should be possible to find all different biomes within a reasonable distance.

**Comment by LionCat3125** [comment]
Thanks
